### ISSUE TITLE
CI による自動 lint

### ISSUE THREAD

**Issue by 1ntegrale9** [DiscordBotPortalJP/database#7]
CI は GitHub Actions
Linter は flake8

でどうでしょう？

**Comment by sizumita** [comment]
いいと思います
ところでコード規約って作りますか？

**Comment by 1ntegrale9** [comment]
> コード規約って作りますか？

作る予定です！実装しながらでも良いかなと思ったけど、
基礎部分は用意しようかな

**Comment by sizumita** [comment]
多分用意したほうがいいかもです。ブランチの命名規則とか、全部まとめたほうがいい気が。

**Comment by 1ntegrale9** [comment]
@sh1ma Discordのやつこっちで返答しておきますー

> linterってflake8できまりなの？

flake8 じゃなくても良いんですが、一旦 flake8 派が多いのでそっちで。
後から black とかに変更しても大丈夫ですー

**Comment by 1ntegrale9** [comment]
自動レビュー系の候補

Python は Lintly
https://github.com/grantmcconnaughey/Lintly

JavaScript, CSS, Docker, dotenv は reviewdog
https://github.com/reviewdog/reviewdog

**Comment by 1ntegrale9** [comment]
Fixed
